import { useRouter } from "next/router";
import { limitText } from "@/utils/limitText";
import useSWR from "swr";
import Image from "next/image";
import { IoIosArrowForward } from "react-icons/io";
import Head from "next/head";
import { FaUserCircle } from "react-icons/fa";
import { motion } from "framer-motion";

const PortfolioDetail = () => {
    const router = useRouter();
    const { id } = router.query;
    const fetcher = (url: string) => fetch(url).then((res) => res.json());
    const { data, error, isLoading } = useSWR(id ? `/api/project` : null, fetcher);
    const portfolioDetail = data?.projects?.find((item: any) => item.id === parseInt(id as string));
    console.log(portfolioDetail);

    if (!portfolioDetail) return <p>Portfolio tidak ditemukan.</p>;
    return (
        <>
            <Head>
                <title>Portfolio | Portfolio Detail</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className="my-22">
                <div className="space-y-6 px-4 bg-[#005b96]/10 p-4 ">
                    <div className="space-y-20 xl:ml-15 items-center justify-center xl:justify-start">
                        <div className="ml-15 flex items-center space-x-2">
                            <p className="text-sm text-gray-800">Home</p>
                            <IoIosArrowForward className="text-gray-800 text-xl" />
                            <p className="text-sm text-gray-800">Profile</p>
                            <IoIosArrowForward className="text-gray-800 text-xl" />
                            <p className="text-sm text-gray-800">News & Article</p>
                        </div>
                    </div>
                </div>
                <div className="max-w-screen-xl px-2 mx-auto mt-10 ">
                    <div className="mt-5 relative h-[300px] xl:h-[600px]">
                        <Image
                            src={portfolioDetail.headerImage}
                            alt={portfolioDetail.title}
                            fill
                            className="object-cover object-center rounded-2xl px-2"
                        />
                    </div>
                    <div>
                        <h1 className="text-xl md:text-3xl font-bold mt-5 mb-2 text-center text-[#005b96]">{portfolioDetail.title}</h1>
                        <hr className="border-2 w-[250px] xl:w-[350px] border-[#80b918] mx-auto" />
                    </div>
                    <div className="mt-10 space-y-6">
                        {portfolioDetail.content.map((item: any, index: number) => {
                            if (item.type === "paragraph") {
                                return (
                                    <motion.div
                                        key={index}
                                        initial={{ opacity: 0, y: 20 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        transition={{ duration: 0.5, delay: index * 0.1 }}
                                    >
                                        <p className="text-sky-950 px-4 mt-4 text-md text-justify">{item.text}</p>
                                    </motion.div>
                                );
                            }

                            if (item.type === "image") {
                                return (
                                    <motion.div
                                        key={index}
                                        initial={{ opacity: 0 }}
                                        animate={{ opacity: 1 }}
                                        transition={{ duration: 0.5, delay: index * 0.1 }}
                                        className="flex flex-col items-center"
                                    >
                                        <Image
                                            src={item.src}
                                            alt={item.caption || "Image"}
                                            width={700}
                                            height={500}
                                            className="object-fit object-center rounded-xl my-2 px-2 xl:px-0"
                                        />
                                        {item.caption && (
                                            <p className="px-[5%] xl:px-[20%] text-center text-sm text-gray-600 italic">{item.caption}</p>
                                        )}
                                    </motion.div>
                                );
                            }

                            return null;
                        })}

                    </div>
                </div>
            </div>
        </>
    );
}

export default PortfolioDetail;