import { IoIosArrowForward } from "react-icons/io";
import Image from "next/image";
import { useLanguage } from "@/components/context/LanguageContext";
import { motion, Variants } from "framer-motion";
import Head from "next/head";
import BenefitsSection from "@/components/BenefitSection";

const fadeUp: Variants = {
    hidden: { opacity: 0, y: 20 },
    visible: (i: number) => ({
        opacity: 1,
        y: 0,
        transition: { duration: 0.6, ease: "easeOut" },
    }),
};

const OurStory = () => {
    const { language } = useLanguage();

    return (
        <>
            <Head>
                <title>Profile | Our Story</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className="my-22">
                <div className="relative w-full h-[300px]">
                    <Image
                        src="/gambar4.jpg"
                        alt="Group Photo"
                        fill
                        className=" object-cover object-center"
                    />
                    <motion.div className="absolute top-1/2 left-0 transform -translate-y-1/2 space-y-6 px-4 bg-gradient-to-r bg-transparent from-white/85 via-[#f0fdf4]/65 to-white/1 w-[75%] h-[300px] p-4 ">
                        <div className="space-y-20 xl:ml-15 items-center justify-center xl:justify-start">
                            <div className="ml-15 flex items-center space-x-2">
                                <p className="text-sm text-gray-800">Home</p>
                                <IoIosArrowForward className="text-gray-800 text-xl" />
                                <p className="text-sm text-gray-800">Profile</p>
                                <IoIosArrowForward className="text-gray-800 text-xl" />
                                <p className="text-sm text-gray-800">Our Story</p>
                            </div>
                            <motion.div className=""
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                transition={{ duration: 0.8 }}>
                                <p className="text-3xl xl:text-4xl font-bold  bg-clip-text bg-gradient-to-r text-gray-700 ml-15">
                                    {language === "en" ? "Our Story" : "Perlajanan Kami"}
                                </p>
                            </motion.div>
                        </div>
                    </motion.div>
                </div>
                <div className="mt-10">
                    <div className="text-center px-2 md:px-4">
                        <h1 className="text-[#005b96] text-2xl xl:text-3xl font-semibold">
                            {language === "en" ? "History Of PT Aruna Hijau Power" : "Perjalanan PT Aruna Hijau Power"}
                        </h1>
                        <hr className="border-2 w-[250px] xl:w-[350px] border-[#80b918] mx-auto my-2" />
                    </div>
                    <motion.div
                        initial={{ opacity: 0, x: -50 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.5 }}
                        viewport={{ once: true, amount: 0.2 }}
                        className="max-w-screen-xl mx-auto space-y-4 mt-10 px-5 xl:px-0">
                        <p className="text-gray-800 text-justify text-md font-light leading-7">
                            {language === "en"
                                ? `Aruna Hijau Power (AHP) is a renewable energy end-to-end solution based in Indonesia, 
                                established as a strategic joint venture between PT Aruna Cahaya Pratama (ACP) 
                                and PT PLN (Persero)—Indonesia’s state-owned electricity company. 
                                The formation of AHP represents a robust public-private partnership aimed at 
                                accelerating clean energy development to support Indonesia’s net-zero emissions target by 2060.`
                                :
                                `Aruna Hijau Power (AHP) adalah solusi energi terbarukan end-to-end yang berbasis di Indonesia, 
                                didirikan sebagai joint venture strategis antara PT Aruna Cahaya Pratama (ACP) 
                                dan PT PLN (Persero)—perusahaan listrik milik negara Indonesia. 
                                Pembentukan AHP merupakan kemitraan publik-swasta yang kokoh yang bertujuan untuk 
                                mempercepat pengembangan energi bersih guna mendukung target nol emisi bersih Indonesia pada tahun 2060.`
                            }
                        </p>
                        <p className="text-gray-800 text-justify text-md font-light leading-7">
                            {language === "en"
                                ? `With the combined strengths of ACP’s project development and commercial, 
                                and PLN’s national electricity infrastructure, regulatory access, and technical capacity, 
                                AHP is uniquely positioned to deliver bankable and scalable renewable energy solutions across Indonesia.`
                                :
                                ` Dengan menggabungkan keunggulan ACP dalam pengembangan proyek dan aspek komersial, serta infrastruktur 
                                listrik nasional PLN, akses regulasi, dan kapasitas teknis, AHP memiliki posisi yang unik untuk menyediakan 
                                solusi energi terbarukan yang layak investasi dan dapat diskalakan di seluruh Indonesia.`
                            }
                        </p>
                        <p className="text-gray-800 text-justify text-md font-light leading-7">
                            {language === "en"
                                ? `AHP operates with the mandate to develop independent power producer (IPP) projects focused on solar PV. 
                                The company focuses on industrial clients, special economic zones, and data center operators seeking long-term 
                                clean energy procurement with trusted developers.`
                                :
                                `AHP beroperasi dengan mandat untuk mengembangkan proyek pembangkit listrik independen (IPP) yang berfokus pada 
                                tenaga surya fotovoltaik (PV). Perusahaan ini berfokus pada klien industri, zona ekonomi khusus, dan operator pusat 
                                data yang mencari pasokan energi bersih jangka panjang dengan pengembang yang terpercaya.`
                            }
                        </p>
                        <p className="text-gray-800 text-justify text-md font-light leading-7">
                            {language === "en"
                                ? `In addition to generating clean electricity from solar energy, AHP offers a unique strategic advantage compared to 
                                other companies: we are officially registered as a user authorized to issue Renewable Energy Certificates (REC) 
                                from i-REC Netherland. This capability provides significant added value to every Solar PV project delivered by AHP.`
                                :
                                `Selain menghasilkan listrik bersih dari energi surya, AHP memiliki keunggulan strategis unik dibandingkan perusahaan 
                                lain: kami secara resmi terdaftar sebagai pengguna yang berwenang untuk menerbitkan Sertifikat Energi Terbarukan (REC) 
                                dari i-REC Belanda. Kemampuan ini memberikan nilai tambah yang signifikan bagi setiap proyek Solar PV yang diselesaikan 
                                oleh AHP.`
                            }
                        </p>
                        <BenefitsSection />
                    </motion.div>
                </div>
            </div>
        </>
    );
}

export default OurStory;