import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { LanguageProvider } from "@/components/context/LanguageContext";
import { Suspense } from "react";
import Loading from "@/components/loading";
import { Manrope } from "next/font/google";
import '@/styles/globals.css';
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import { OpenProvider } from "@/components/context/isActived";

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-manrope', // optional
});
export default function App({ Component, pageProps: { session, ...pageProps } }: AppProps) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ahp-logo.ico" />
      </Head>
      <main className={manrope.className}>
        <LanguageProvider>
          <OpenProvider>
            <SessionProvider session={session}>
              <Suspense fallback={<Loading />}>
                <Component {...pageProps} />
              </Suspense>
              <Toaster position="top-right" reverseOrder={false}
                toastOptions={{
                  duration: 1500, // default semua toast 3 detik
                }} />
            </SessionProvider>
          </OpenProvider>
        </LanguageProvider>
      </main>
    </>
  );
}
