// pages/profile/vision-mission.tsx

import { useLanguage } from "@/components/context/LanguageContext";
import { IoIosArrowForward } from "react-icons/io";
import Image from "next/image";
import { motion } from "framer-motion";
import { GrAchievement } from "react-icons/gr";
import { MdHighlight } from "react-icons/md";
import { SiLightning } from "react-icons/si";
import { FaBoltLightning } from "react-icons/fa6";
import { FaGlobeAsia } from "react-icons/fa";
import { FaDartLang } from "react-icons/fa6";
import Head from "next/head";

const VisionMission = () => {
    const { language } = useLanguage();

    return (
        <>
            <Head>
                <title>Profile | Vision & Mission</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <div className="py-22">
                {/* Banner with breadcrumb */}
                <div className="relative w-full h-[300px]">
                    <Image
                        src="/gambar4.jpg"
                        alt="Group Photo"
                        fill
                        className=" object-cover object-center"
                    />
                    <div className="absolute top-1/2 left-0 transform -translate-y-1/2 space-y-6 px-4 bg-gradient-to-r bg-transparent from-white/85 via-[#f0fdf4]/65 to-white/1 w-[75%] h-[300px] p-4 ">
                        <div className="space-y-20 xl:ml-15 items-center justify-center xl:justify-start">
                            <div className="ml-15 flex items-center space-x-2">
                                <p className="text-sm text-gray-800">Home</p>
                                <IoIosArrowForward className="text-gray-800 text-xl" />
                                <p className="text-sm text-gray-800">Profile</p>
                                <IoIosArrowForward className="text-gray-800 text-xl" />
                                <p className="text-sm text-gray-800">Vison & Mission</p>
                            </div>
                            <motion.div className=""
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                transition={{ duration: 0.8 }}
                            >
                                <p className="text-3xl xl:text-4xl font-bold  bg-clip-text bg-gradient-to-r text-gray-700 ml-15">
                                    {language === "en" ? "Vision & Mission" : "Visi & Misi"}
                                </p>
                            </motion.div>
                        </div>
                    </div>
                </div>

                {/* Description */}
                <div>
                    <p className="text-gray-600 text-md text-center font-light py-8 px-4 md:px-20">
                        {language === "en"
                            ? "PT Aruna Hijau Power consistently upholds its vision and mission as a cornerstone in fostering long-term environmental sustainability."
                            : "PT Aruna Hijau Power secara konsisten menjunjung tinggi visi dan misinya sebagai landasan dalam mendorong keberlanjutan lingkungan jangka panjang."}
                    </p>
                </div>

                {/* Vision & Mission Content */}
                <motion.div
                    className="container px-[8%] grid grid-cols-1 xl:grid-cols-2 w-full h-full"
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                    viewport={{ once: true, amount: 0.2 }}
                >
                    {/* Vision */}
                    <motion.div
                        initial={{ opacity: 0, x: -50 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.4, delay: 0.2 }}
                        viewport={{ once: true }}
                        className="flex items-start gap-x-5 p-4"
                    >
                        <div className="mt-1">
                            <GrAchievement className="text-3xl text-[#005b96]" />
                        </div>
                        <div>
                            <h2 className="text-2xl font-semibold text-[#005b96]">
                                {language === "en" ? "Vision" : "Visi"}
                            </h2>
                            <hr className="border-2 w-[60px] border-[#80b918]" />
                            <div className="space-y-4 mt-5">
                                <div className="text-gray-700 text-sm flex items-center gap-x-5">
                                    <FaGlobeAsia className="text-teal-500 w-10 h-10 xl:w-8 xl:h-8" />
                                    <p className="text-justify">
                                        {language === "en"
                                            ? "To become a leading renewable energy company in Indonesia, committed to sustainability and social responsibility."
                                            : "Menjadi perusahaan energi terbarukan terkemuka di Indonesia yang berkomitmen pada keberlanjutan dan tanggung jawab sosial."}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </motion.div>

                    {/* Mission */}
                    <motion.div
                        initial={{ opacity: 0, x: 50 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.4, delay: 0.4 }}
                        viewport={{ once: true }}
                        className="flex items-start justify-center gap-x-4 p-4"
                    >
                        <div className="mt-1">
                            <FaDartLang className="text-3xl text-[#005b96]" />
                        </div>
                        <div>
                            <h2 className="text-2xl font-semibold text-[#005b96]">
                                {language === "en" ? "Mission" : "Misi"}
                            </h2>
                            <hr className="border-2 w-[80px] border-[#80b918]" />
                            <div className="space-y-7 mt-5">
                                <div className="flex gap-x-4 justify-start items-start">
                                    <MdHighlight className="text-teal-500 w-12 h-10 xl:w-10 xl:h-10" />
                                    <p className="text-gray-700 text-sm text-justify">
                                        {language === "en"
                                            ? "To develop and manage renewable energy plants with a focus on efficiency and positive social impact."
                                            : "Mengembangkan dan mengelola pembangkit energi terbarukan dengan fokus pada efisiensi dan dampak sosial yang positif."}
                                    </p>
                                </div>
                                <div className="text-gray-700 text-justify text-sm flex justify-start items-start gap-x-5">
                                    <FaBoltLightning className="text-teal-500 w-8 h-8 xl:w-7 xl:h-7 ml-1" />
                                    <p>
                                        {language === "en"
                                            ? "Delivering green energy solutions through efficient power plant development with real environmental and social impact."
                                            : "Menyediakan solusi energi hijau melalui pembangunan pembangkit yang efisien dan berdampak nyata bagi lingkungan dan masyarakat."}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                </motion.div>
            </div>
        </>
    );
};

export default VisionMission;
